services:
  
  purchasingorderDB:
    image: mcr.microsoft.com/mssql/server:2022-latest

  messagebroker:
    image: rabbitmq:management

  purchasingorder.api:
    image: ${DOCKER_REGISTRY-}purchasingorderapi
    build:
      context: .
      dockerfile: src/PurchasingOrder.API/Dockerfile
  